### ISSUE TITLE
NoSuchMethodError

### ISSUE THREAD

**Issue by asgorh** [millennialmedia/intellibot#112]
Hi,

There is a problem with 0.6.7 version on both Windows/Linux builds. There are many:
11:30:00 NoSuchMethodError: com.jetbrains.python.psi.PyClass.visitClassAttributes(Lcom/intellij/util/Processor;Z)Z

errors once I try to use autofill with keyword name.

More details: http://pastebin.com/k3v4xrfc

**Comment by bkvaughan** [comment]
This affects Mac as well.

**Comment by alex-klimovich** [comment]
Reporoduced in new version of PyCharm - 5.0

**Comment by yahman72** [comment]
same issue here + an additional one with (probably same root cause)
`12:26:15 NoSuchMethodError: com.jetbrains.python.psi.PyClass.visitMethods(Lcom/intellij/util/Processor;Z)Z`
This comes more often: I get it every time I switch between tabs in PyCharm and when I switch between programs (e.g. PyCharm --> Browser --> PyCharm)

**Comment by mtrubs** [comment]
the release of intellij and pycharm has messed up backwards compatibility.  Since they have both been updated now, I can address this issue uniformly so it should make things easier.  I will try to get something done today and published tonight.

**Comment by mtrubs** [comment]
#110
