### ISSUE TITLE
Can't support to detect python package

### ISSUE THREAD

**Issue by yili1992** [millennialmedia/intellibot#134]
my project
|_application  (python package)
|_connections (python package)
global.robot

my global.robot
Library application
Library connections 

Intellibot cant  detect my python package

**Comment by mtrubs** [comment]
PyCharm, Ultimate or Community?  If community I am about to release a new version to fix that.

Otherwise, have you looked at this wiki to make sure your project is setup correctly.  If your project can compile your python files without error then the robot files should as well.

https://github.com/millennialmedia/intellibot/wiki/Python-Interpreter

**Comment by yili1992** [comment]
It's Community

**Comment by yili1992** [comment]
Intellibot just to match python file , can't to match python package

**Comment by mtrubs** [comment]
this should be fixed in the next release which i hope to get out soon.

**Comment by yili1992** [comment]
the problem still exists
