### ISSUE TITLE
search dynamic keywords at   sibling library 

### ISSUE THREAD

**Issue by youwi** [millennialmedia/intellibot#199]
I want  support SeleinumLibrary  dynamic keywords.
here is some example code.
Not yet tested for stability.
```java
// com.millennialmedia.intellibot.psi.element.HeadingImpl.java
// line 389 
//  +  findChildrenClass(files, "keywords");

  /* 
     * search sibling library by keywords
     * patch for SeleniumLibrary dynamic keywords
     * support all libraries that contain "keywords" package.
     * @param files  all pyClass
     * @param libraryName  default search is keywords.
     */
    void findChildrenClass(Collection files,String libraryName){

        Collection<PyFile> fileList=PyModuleNameIndex.find(libraryName,getProject(),true);
        for(PyFile pyFile:fileList){
            PyFile nextFile=pyFile;

            while (nextFile!=null){
                PsiElement[] all= nextFile.getChildren();
                for(PsiElement psiElement:all){
                    if(psiElement instanceof PyClass){
                        files.add(new RobotPythonClass(((PyClass) psiElement).getName(), (PyClass) psiElement, ImportType.LIBRARY));
                    }
                }
                nextFile= (PyFile) nextFile.getNextSibling();
            }
        }
    }
```

# do you have some idea better?

**Comment by youwi** [comment]
i forked that @ https://github.com/youwi/intellibot

**Comment by outcatcher** [comment]
@youwi Not being strictly correct, works as desired :+1:  
Tested with `SeleniumLibrary` and my custom library using `/keywords` directory for storing keywords

**Comment by YK1434** [comment]
@youwi  @outcatcher 
Am i missing on something ? Downloaded and Installed plugin but still the issue persists

**Comment by frankvanderkuur** [comment]
Hi Youwi,
Thank you so much for putting some work into the Intellibot library to fix the dynamic library problem. I think you're on the correct path in solving this problem, since I expect more libraries will follow the Selenium path and will be created as dynamic libraries.

I've tested your forked .jar in my Pyharm installation and although a great part of the Selenium Library works again, there are also a bunch of keywords that don't get autocompleted or resolved as a correct Selenium keyword. I've tested this among a few different installations and it seems all the keywords come from the same six keyword files. I didn't find the reason of the problem, but maybe it helps you out.

I've tested this again the 3.1.1 version of the Robot Selenium Library. These are the system's I've tested:

Windows 7, Pycharm 2017.1
Windows 10, Pycharm 2018.1
Mac OS High Sierra 10.13, Pycharm 2017.1

In all cases the keywords of the following library files aren't recognized:
alert.py
cookie.py
element.py
frames.py
waiting.py
window.py

I hope this helps you out. If there is anything else I can do to help, please let me know!

**Comment by youwi** [comment]
fixed. download new jar.

**Comment by youwi** [comment]
core code:
```
   void findChildrenClass(Collection files,String libraryName){

        Collection<PyFile> fileList = PyModuleNameIndex.find(libraryName, getProject(), true);
        List<PsiFile> allFiles = new ArrayList<PsiFile>();
        for (PyFile pyFile : fileList) {
            if (pyFile.getParent() != null){
                allFiles.addAll(Arrays.asList(pyFile.getParent().getFiles()));
            }
        }
        for (PsiFile pyFile : allFiles) {
            PsiFile nextFile = pyFile;
            while (nextFile != null) {
                PsiElement[] all = nextFile.getChildren();
                for (PsiElement psiElement : all) {
                    if (psiElement instanceof PyClass) {
                        files.add(new RobotPythonClass(((PyClass) psiElement).getName(), (PyClass) psiElement, ImportType.LIBRARY));
                    }
                }
                nextFile = (PyFile) nextFile.getNextSibling();
            }
        }
    }
```

**Comment by frankvanderkuur** [comment]
Hi Youwi,

Great job! I just retested your new jar in the same 3 environments and now it works like a charm. Thank you very much for your work, I think you've made many Robot Framework / Pycharm users very happy with this new version!

Well done!

**Comment by robotframeworktutorial** [comment]
Thank you for this! I have 8,000+ students taking my Robot Framework training courses who really needed this update. 

Are you a Slack user? Would you please join us there? We have an Intellibot channel there and would love to have you as part of the community.

**Comment by mtrubs** [comment]
CC @DanielPBak might we worth trying to merge into your efforts.
