### ISSUE TITLE
Installing Intellibot for selenium still not recognizing robot keywords

### ISSUE THREAD

**Issue by MarialenaShiamma** [millennialmedia/intellibot#229]
Hello,

I have installed intellibot for selenium and i can still not see any auto-complete suggestions or anything when I click Ctrl+Click on a keyword eg Close.

Information about my environment based on About section of Pycharm:

> PyCharm 2019.3.3 (Community Edition)
> Build #PC-193.6494.30, built on February 6, 2020
> Runtime version: 11.0.5+10-b520.38 amd64
> VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
> Windows 10 10.0
> GC: ParNew, ConcurrentMarkSweep
> Memory: 1963M
> Cores: 8
> Registry: 
> Non-Bundled Plugins: com.millennialmedia.intellibot@SeleniumLibrary Patched, org.intellij.plugins.markdown

Any ideas what might be wrong?

![image](https://user-images.githubusercontent.com/5478955/77442888-622fc600-6df3-11ea-8b17-3117f1ee58d5.png)

**Comment by ghost** [comment]
I just wanted to chime in. I too am experiencing this exact issue. It appears that the selenium(patched) plugin fixes this issue, but introduces a more severe bug - you can no longer control-click to navigate to definitions of the keyword/usage. 

I know it is annoying, but a temporary workaround that I use for this, since there are only a handful of core Selenium keywords I use..... Make a new keyword which uses the keyword, maybe you can even enhance it for your use case... 

**For example:**

Click Element   ${element}                   This would normally show as a syntax error even though it is 
                                                            correct (the current bug)

You would make a keyword as follows:

Click My Element 
      [Arguments]    ${element}
      Click Element   ${element}

You would call the keyword the same way:
Click My Element   ${element}


From there on out, for the rest of your keywords, you would just use the Click My Element. This eliminates the red highlighting in all areas except the keyword definition of Click My Element which is great to just 1 single location you will not use again. 

This has worked well for me, as I need the functionality to navigate throughout the project that intellibot provides.

**Comment by MarialenaShiamma** [comment]
> t, for the rest of your keywords, you would just use the Click M

Thanks for the suggestion, i will try that.

**Comment by MarialenaShiamma** [comment]
> I just wanted to chime in. I too am experiencing this exact issue. It appears that the selenium(patched) plugin fixes this issue, but introduces a more severe bug - you can no longer control-click to navigate to definitions of the keyword/usage.
> 
> I know it is annoying, but a temporary workaround that I use for this, since there are only a handful of core Selenium keywords I use..... Make a new keyword which uses the keyword, maybe you can even enhance it for your use case...
> 
> **For example:**
> 
> Click Element ${element} This would normally show as a syntax error even though it is
> correct (the current bug)
> 
> You would make a keyword as follows:
> 
> Click My Element
> [Arguments] ${element}
> Click Element ${element}
> 
> You would call the keyword the same way:
> Click My Element ${element}
> 
> From there on out, for the rest of your keywords, you would just use the Click My Element. This eliminates the red highlighting in all areas except the keyword definition of Click My Element which is great to just 1 single location you will not use again.
> 
> This has worked well for me, as I need the functionality to navigate throughout the project that intellibot provides.

Thanks for the suggestion, i will try that.

**Comment by ps1logi** [comment]
please try email mtrubs@gmail.com he can help you fix the issue

**Comment by tranhuyimip** [comment]
Same issue,  i can't see any auto-complete suggestions from keyword

**Comment by skadiyala-mdsol** [comment]
same issue here, cannot see auto complete suggestions on keyword.

**Comment by frankvanderkuur** [comment]
You can try this fork by lte2000, this solved the problem for me.

https://github.com/lte2000/intellibot

**Comment by ps1logi** [comment]
@frankvanderkuur thanks for sharing

**Comment by MarialenaShiamma** [comment]
I had used this one and it solved my issue:
https://github.com/youwi/intellibot

Closing this issue
